"""Run and evaluate the paper's strategy versions, and the ablation ladder, on the TRAIN
period. (Phases 3-4)

    python -m scripts.03_run_backtests

The test period is deliberately not run here; it is touched once, in 06_run_test.py.
Only the paper's versions run here: the own versions are judged on train by 05_own_strategy.py,
out of sample per walk-forward block (the ML model would be in-sample on the whole train period).
Writes results/backtests/, results/figures/train_*.png, results/train_report.md and logs
every run to results/experiment_log.csv.
"""

from src.config import BACKTEST_DIR, RESULTS_DIR, load_research, load_strategies
from src.engine.backtest import MarketData
from src.evaluation.ablation import run_ablation
from src.evaluation.report import evaluate

PAPER_VERSIONS = ["base", "vwap_stop", "final"]
ABLATION_COLUMNS = ["band_reference", "stop", "sizing", "total_return", "annual_return",
                    "annual_gross", "annual_volatility", "sharpe", "max_drawdown",
                    "return_at_10pct_vol", "trades"]


def main() -> None:
    research = load_research()
    data = MarketData.load()
    BACKTEST_DIR.mkdir(parents=True, exist_ok=True)
    paper = {name: cfg for name, cfg in load_strategies().items() if name in PAPER_VERSIONS}
    table = evaluate(paper, research, data, "train", research.train_start, research.train_end)

    cols = ["annual_return", "annual_volatility", "sharpe", "sharpe_ci_low", "sharpe_ci_high",
            "max_drawdown", "alpha", "beta", "placebo_p_value", "deflated_sharpe_prob"]
    print(f"TRAIN {research.train_start} -> {research.train_end}\n")
    print(table[cols].astype(float).round(3).to_string())
    print("\nFull report: results/train_report.md")

    ablation = run_ablation(load_strategies("ablation.yaml"), research, data, "train",
                            research.train_start, research.train_end)[ABLATION_COLUMNS]
    shown = ablation.copy()
    for col in ["total_return", "annual_return", "annual_gross", "annual_volatility", "max_drawdown",
                "return_at_10pct_vol"]:
        shown[col] = ablation[col].map(lambda v: "" if v != v else f"{v:.1%}")
    shown["sharpe"] = ablation["sharpe"].map("{:.2f}".format)
    shown["trades"] = ablation["trades"].astype(int)
    (RESULTS_DIR / "train_ablation.md").write_text(
        "# Ablation on the train period (net of costs)\n\n_Generated by `scripts/03_run_backtests.py`._\n\n"
        + shown.to_markdown() + "\n")
    print("\nABLATION (train)\n" + shown.to_string())


if __name__ == "__main__":
    main()
