"""Own-version research, Stage 1: diagnose the final strategy on the TRAIN period only.

    python -m scripts.04b_diagnose

1. P&L split by year: opportunity (trend days) x capture (earnings on them) + cost (other days)
2. Trade level: which features known at entry separate good trades from bad ones
3. The 50 worst trades: which patterns are over-represented, plus charts to read by hand
Writes results/diagnose_report.md and results/figures/diagnose_*.png.
"""

import numpy as np
import pandas as pd

from src import plots
from src.config import RESULTS_DIR, load_research, load_strategies
from src.engine.backtest import MarketData, prepare, simulate
from src.evaluation import diagnostics as dg, trade_features

FEATURES = ["breakout_sigma", "vwap_distance_sigma", "rel_volume_30m", "rel_realized_vol", "efficiency",
            "rel_opening_range", "gap_with_trade", "implied_vs_realized", "vix_open", "entry_minute"]
N_WORST = 50


def fmt(df: pd.DataFrame, pct: set[str] = frozenset()) -> str:
    out = df.copy().astype(object)
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            pattern = "{:.1%}" if col in pct else "{:.0f}" if col in ("days", "trades") else "{:.3f}" \
                if col.startswith(("auc", "rho", "q_")) else "{:.2f}"
            out[col] = df[col].map(lambda v: "" if pd.isna(v) else pattern.format(v))
    return out.to_markdown()


def main() -> None:
    research = load_research()
    data = MarketData.load()
    prep = prepare(load_strategies()["final"], data, research.train_start, research.train_end)
    result = simulate(prep, prep.rule_positions(), research)
    days = result.daily.index
    daily = data.daily.loc[days]

    # ---- 1. P&L split by year
    expansion = dg.expansion_ratio(daily, data.minute_feats)
    split = dg.pnl_split(result.daily["ret"], expansion, prep.leverage, daily["ret_oc"])

    # ---- 2. trade level
    trades = trade_features.build(prep, result, data)
    screen = dg.feature_screen(trades, FEATURES)
    by_entry = trades.groupby("entry_time")["return_1x"].agg(["size", "mean"]).rename(
        columns={"size": "trades", "mean": "avg_1x_bps"}).assign(avg_1x_bps=lambda t: t["avg_1x_bps"] * dg.BPS)

    # ---- 3. worst trades
    day_move = trades["date"].map(daily["ret_oc"])
    after_14 = trades["exit_time"].isin(["14:30", "15:00", "15:30", "close"])
    turbulent = trades["rel_realized_vol"] > trades["rel_realized_vol"].quantile(0.8)
    flags = {
        "entered at 10:00 or 10:30": trades["entry_time"].isin(["10:00", "10:30"]),
        "entered 12:00-13:30 (midday)": trades["entry_time"].isin(["12:00", "12:30", "13:00", "13:30"]),
        "entered 14:30 or later": trades["entry_time"].isin(["14:30", "15:00", "15:30"]),
        "re-entry (2nd+ trade of the day)": trades["sequence"] != "1st trade",
        "re-entry in the reversed direction": trades["reentry"] == "reversed direction",
        "Wednesday": trades["weekday"] == "Wed",
        "Wednesday, held through 14:00 (FOMC time)": (trades["weekday"] == "Wed")
                                                     & (trades["entry_time"] < "14:00") & after_14,
        "breakout against the overnight gap": trades["gap_with_trade"] < 0,
        "at the 4x leverage cap": trades["leverage"] >= 3.999,
        "stopped within 30 minutes": trades["exit_time"] == trades["entry_time"].map(
            lambda t: f"{(int(t[:2]) * 60 + int(t[3:]) + 30) // 60:02d}:{(int(t[3:]) + 30) % 60:02d}"),
        "day closed against the trade (explanatory)": trades["side"] * day_move < 0,
        "today already turbulent (top 20% realized vol so far)": turbulent,
    }
    patterns = dg.worst_trade_patterns(trades, flags, N_WORST)
    worst = trades.nsmallest(N_WORST, "contribution")
    worst_table = worst.set_index("date")[["weekday", "side_name", "entry_time", "exit_time", "sequence",
                                           "contribution", "leverage", "breakout_sigma", "rel_realized_vol",
                                           "rel_opening_range", "gap_with_trade", "vix_open"]]
    worst_table.index = worst_table.index.strftime("%Y-%m-%d")

    # ---- figures
    plots.pnl_split_chart(split, "Final strategy by year: opportunity, capture, cost (train)", "diagnose_pnl_split")
    plots.feature_screen_chart(screen, "Which conditions at entry go with better trades? (train)", "diagnose_features")
    worst_days = worst.drop_duplicates("date")["date"].head(6)
    plots.day_panels(data.minute, data.minute_feats, result.trades,
                     result.daily.loc[worst_days, "ret"], "Days of the six worst trades (train)", "diagnose_worst_days")

    lines = ["# Own-version research, Stage 1: diagnosis of the final strategy (train 2016–2022)", "",
             "_Generated by `scripts/04b_diagnose.py`. Train period only; the test period is not used._", "",
             "## 1. P&L split by year: opportunity x capture + cost", "",
             "Opportunity = share of days closing outside the noise area. Capture = mean return on those "
             "days; capture_ratio = their total vs a perfect-hindsight open-to-close trade at the same "
             "leverage. Cost = mean return on the other days. The three effects split each year's "
             "deviation from the whole-period mean daily return exactly (bps/day). "
             "Figure: diagnose_pnl_split.png.", "",
             fmt(split, {"opportunity", "capture_ratio", "annual_return"}), "",
             "## 2. Which conditions at entry separate good trades from bad ones", "",
             f"{len(trades)} trades; {trades['win'].mean():.0%} win, {trades['held_to_close'].mean():.0%} "
             "are held to the close. AUC (hit rate) and rank correlation with the 1x return (payoff), with "
             "q-values corrected for testing all features. Figure: diagnose_features.png.", "",
             fmt(screen), "",
             "### Average 1x return by entry time (bps)", "", fmt(by_entry), "",
             f"## 3. The {N_WORST} worst trades", "",
             "How often each pattern appears among the worst trades vs all trades (ratio > 1 = over-"
             "represented). Figure: diagnose_worst_days.png.", "",
             fmt(patterns, {"worst_trades", "all_trades"}), "", fmt(worst_table.head(20), {"contribution"}), ""]
    (RESULTS_DIR / "diagnose_report.md").write_text("\n".join(lines))
    print("Report: results/diagnose_report.md")


if __name__ == "__main__":
    main()
