"""Evaluate the strategies on the TEST period (2023 onward) and the post-publication slice.
(Phase 7)

    python -m scripts.06_run_test      (run 03_run_backtests first)

Every strategy evaluated here must already be frozen. The paper's versions qualify from the
start (their rules come from the paper, nothing is tuned on our data); the own strategy is
added once it is frozen. Every run is logged in results/experiment_log.csv.

Also writes results/replication_report.md: our final strategy vs the paper's published monthly
returns, over train and test together; and, for the own versions (SECOND use of the test period,
see config/research.yaml), results/own_vs_final_test.md with the paired comparisons and the
verdicts fixed in advance in docs/own_version_research.md.
"""

import pandas as pd

from src.config import BACKTEST_DIR, RESULTS_DIR, load_research, load_strategies
from src.engine.backtest import MarketData
from src.evaluation import metrics, replication, stats
from src.evaluation.report import evaluate

SHOW = ["total_return", "annual_return", "annual_volatility", "sharpe", "max_drawdown"]
MAIN, CHALLENGER = "own_turbulence", "own_ml_vol"     # roles fixed before the test run


def verdict(d: dict) -> str:
    """The pre-registered reading of a paired Sharpe difference."""
    if d["ci_low"] > 0:
        return "improvement, 95% interval above zero"
    if d["difference"] > 0:
        return "points the right way, not significant (interval includes zero)"
    return "no improvement"


def own_report(periods: dict[str, str], last_day) -> str:
    sections = ["# Own versions vs final: test period (SECOND use) and post-publication\n\n"
                "_Generated by `scripts/06_run_test.py`. Both own versions were frozen before this run "
                "(docs/own_version_research.md); both are reported whatever the result. Sharpe differences: "
                "paired block bootstrap, 95% interval._"]
    for period, start in periods.items():
        ret = {n: pd.read_parquet(BACKTEST_DIR / f"{n}_{period}_daily.parquet")["ret"] for n in ("final", MAIN, CHALLENGER)}
        rows = []
        for n, r in ret.items():
            d = stats.sharpe_difference(r, ret["final"]) if n != "final" else None
            rows.append({"version": n, "annual_return": f"{metrics.annual_return(r):.1%}",
                         "annual_volatility": f"{metrics.annual_volatility(r):.1%}", "sharpe": metrics.sharpe(r),
                         "max_drawdown": f"{metrics.max_drawdown(r):.1%}",
                         "sharpe gain vs final [95% CI]": "" if d is None else
                         f"{d['difference']:+.2f} [{d['ci_low']:+.2f}, {d['ci_high']:+.2f}]",
                         "verdict": "" if d is None else verdict(d)})
        pair = stats.sharpe_difference(ret[CHALLENGER], ret[MAIN])
        years = sorted(set(ret["final"].index.year))
        per_year = pd.DataFrame({y: {f"gain {n}": metrics.sharpe(ret[n][ret[n].index.year == y])
                                     - metrics.sharpe(ret["final"][ret["final"].index.year == y]) for n in (MAIN, CHALLENGER)}
                                 for y in years}).T
        sections.append(f"## {period.replace('_', ' ')}: {start} – {last_day:%Y-%m-%d}\n\n"
                        + pd.DataFrame(rows).to_markdown(index=False, floatfmt=".2f")
                        + f"\n\n- Challenger vs main ({CHALLENGER} vs {MAIN}): {pair['difference']:+.2f} "
                          f"[{pair['ci_low']:+.2f}, {pair['ci_high']:+.2f}] -> "
                          f"{'challenger better' if pair['difference'] > 0 else 'main candidate kept'}\n\n"
                        + "Sharpe gain vs final by year (partial years included):\n\n" + per_year.to_markdown(floatfmt="+.2f"))
    return "\n\n".join(sections) + "\n"


def main() -> None:
    research = load_research()
    strategies = load_strategies()
    data = MarketData.load()

    tables = {}
    periods = {"test": research.test_start, "post_publication": research.post_publication_start}
    for period, start in periods.items():
        tables[period] = evaluate(strategies, research, data, period, start, None)
        print(f"\n{period.upper()} {start} -> {data.daily.index[-1]:%Y-%m-%d}")
        print(tables[period][SHOW].astype(float).round(3).to_string())

    # ---- replication: final strategy over train + test vs the paper's monthly table
    daily = pd.concat([pd.read_parquet(BACKTEST_DIR / f"final_{p}_daily.parquet")["ret"] for p in ("train", "test")])
    print("\n" + replication.write_report(daily))

    if {MAIN, CHALLENGER} <= set(strategies):
        report = own_report(periods, data.daily.index[-1])
        (RESULTS_DIR / "own_vs_final_test.md").write_text(report)
        print("\n" + report)


if __name__ == "__main__":
    main()
