"""Checks data quality and writes the report."""

import pandas as pd

from src.data.clean import MAX_FILLED_SHARE

OUTLIER_MOVE = 0.01


def _bps(x: pd.Series) -> pd.Series:
    return x * 1e4


def check(minute: pd.DataFrame, daily: pd.DataFrame) -> dict:
    real = minute[~minute["is_filled"]]
    one_min_ret = real.groupby("date")["close"].pct_change()
    outliers = real.loc[one_min_ret.abs() > OUTLIER_MOVE, ["date", "minute", "open", "close", "volume"]]

    open_gap_bps = _bps(daily["open"] / daily["official_open"] - 1).abs()
    close_gap_bps = _bps(daily["last_bar_close"] / daily["close"] - 1).abs()

    return {
        "first_day": daily.index.min(), "last_day": daily.index.max(),
        "n_days": len(daily), "n_minutes": len(minute),
        "n_half_days": int(daily["is_half_day"].sum()),
        "n_invalid": int((~daily["is_valid"]).sum()),
        "invalid_days": daily.loc[~daily["is_valid"], ["n_minutes", "n_filled", "filled_share"]],
        "filled_share_total": minute["is_filled"].mean(),
        "worst_filled_days": daily.nlargest(5, "filled_share")[["n_minutes", "n_filled", "filled_share"]],
        "missing_official_bar": int(daily["official_open"].isna().sum()),
        "open_gap_bps": open_gap_bps.describe(percentiles=[0.5, 0.95, 0.99]),
        "close_gap_bps": close_gap_bps.describe(percentiles=[0.5, 0.95, 0.99]),
        "outliers": outliers,
        "dividends": daily.loc[daily["dividend"] > 0, ["dividend", "prev_close"]],
        "missing_vix": int(daily["vix_open"].isna().sum()),
    }


def _fmt_dates(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out.index = out.index.strftime("%Y-%m-%d %H:%M" if getattr(out.index, "tz", None) else "%Y-%m-%d")
    return out.drop(columns="date", errors="ignore")


def write_report(results: dict, path) -> None:
    r = results
    divs = r["dividends"]
    lines = [
        "# Data quality report",
        "",
        "_Generated by `scripts/02_build_dataset.py`; do not edit by hand._",
        "",
        "## Coverage",
        f"- Period: {r['first_day']:%Y-%m-%d} to {r['last_day']:%Y-%m-%d}",
        f"- Trading days: {r['n_days']:,} ({r['n_half_days']} half-days closing at 13:00)",
        f"- Regular-session minutes: {r['n_minutes']:,}",
        f"- Days without an official (Yahoo) daily bar: {r['missing_official_bar']}",
        f"- Days without VIX: {r['missing_vix']}",
        "",
        "## Missing minutes",
        f"- Filled minutes overall: {r['filled_share_total']:.3%} (flat bar at last close, zero volume)",
        "- Not all filled minutes are data errors: the 14-minute gaps in March 2020 are the "
        "market-wide circuit-breaker halts, when no trades printed.",
        f"- Days marked invalid (> {MAX_FILLED_SHARE:.0%} filled): {r['n_invalid']}",
        "",
        "Worst days:",
        "",
        _fmt_dates(r["worst_filled_days"]).to_markdown(floatfmt=".3f"),
        "",
        "## Minute bars vs official daily open/close (Yahoo)",
        "First 1-min open vs official open, and last 1-min close vs official close, absolute difference in bps.",
        "The official close is the closing auction, which the last minute bar does not include, so small "
        "differences are expected; on extreme days (e.g. 2025-04-09) they can reach ~1%. "
        "The daily table therefore uses the official close.",
        "",
        pd.DataFrame({"open (bps)": r["open_gap_bps"], "close (bps)": r["close_gap_bps"]})
          .to_markdown(floatfmt=".2f"),
        "",
        f"## 1-minute moves larger than {OUTLIER_MOVE:.0%}",
        f"{len(r['outliers'])} bars. Real market events (Feb 2018, Covid, Apr 2025 tariffs) are kept; "
        "only clear bad ticks would be removed.",
        "",
        _fmt_dates(r["outliers"].head(20)).to_markdown(floatfmt=".2f") if len(r["outliers"]) else "None.",
        "",
        "## Dividends",
        f"{len(divs)} ex-dividend days, total ${divs['dividend'].sum():.2f} per share. "
        "On these days `prev_close_adj = prev_close - dividend`, so the ex-dividend drop "
        "is not read as an overnight gap.",
        "",
        _fmt_dates(divs.tail(8)).to_markdown(floatfmt=".4f"),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
